### ISSUE TITLE
PDO fails

### ISSUE THREAD

**Issue by TheBeachMaster** [RayceeM/dashnexlink#3]
A strange error is encountered in connecting to MySQL using PDO.
### How to reproduce 
1. In the `database_connection.php` file, open a connection via PDO as follows:

 `try { 

    $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password); 

    // set the PDO error mode to exception 

    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); 

    echo "Connected successfully";  

    } 
catch(PDOException $e) 
    { 

    echo "Connection failed: " . $e->getMessage(); 

    } ` 
2.  Serve PHP and navigate to `http://<host>:<port>/database_connection.php` 
3. You should get the following error 
  ***Connection failed: could not find driver***

**Comment by TheBeachMaster** [comment]
# Fix 
1. Navigate to PHP install directory 
2. Open `php.ini-*` file 
![ini1](https://user-images.githubusercontent.com/9129843/30565416-d5e14048-9cd0-11e7-9569-973b87ce9758.PNG) 
3. enable `pdo_mysql` and `php_mysql` 
 
> Fix is being invetigated

**Comment by TheBeachMaster** [comment]
# LOST 
Which part of the project is this? 
Am currently running on IIS...
![login](https://user-images.githubusercontent.com/9129843/30567464-2d028910-9cd9-11e7-8dba-ae8f6a9d96e5.PNG)

**Comment by RayceeM** [comment]
ooh that  is the login page.if you imported the sql code then you can use my credentials

**Comment by TheBeachMaster** [comment]
***Is it supposed to be blank?*** 
![admin](https://user-images.githubusercontent.com/9129843/30602085-3b6bf610-9d6c-11e7-93af-727a824126fa.PNG)

**Comment by TheBeachMaster** [comment]
1. PDO issue can be closed..by enabling PDO in the .ini file...  
![pdo](https://user-images.githubusercontent.com/9129843/30613435-bdcbfd0c-9d90-11e7-8c39-b14ffe8677a9.PNG) 
![iispdo](https://user-images.githubusercontent.com/9129843/30613459-e0d55500-9d90-11e7-9918-b98deeefec32.PNG)  
> Look at [this documentation](http://php.net/manual/en/pdo.installation.php) on how to enable PDO for Xampp
